name = "kbc-email-marketing"
main = "src/index.ts"
compatibility_date = "2024-01-01"

[[d1_databases]]
binding = "DB"
database_name = "kiamichi-biz-connect-db"
database_id = "e8b7b17a-a93b-4b61-92ad-80b488266e12"

[env.production]
name = "kbc-email-marketing"

[env.preview]
name = "kbc-email-marketing-preview"
